@startuml

title __SERVERUS's Class Diagram__\n

  namespace ServerUS {
    class ServerUS.ServerUS {
        {static} + NAME_REG : String
        {static} + REG_NAME : String
        {static} + connection_icescrum : Connection
        {static} + connection_userstorydb : Connection
        {static} - URL_Icescrum : String
        {static} - URL_UserStoryDB : String
        {static} - host : String
        {static} - password : String
        {static} - port : String
        {static} - user : String
        + ServerUS()
        + check_db()
        + check_db_resultSet()
        + downloardUserStory()
        + insertDDL_userStory()
        + loadUserStory_DB()
        {static} + main()
        + searchByTag()
        + serachAllUserStoryfromDatabase_Icescrum()
        + testRMI()
        + viewUserStoryPNG()
    }
  }
  

  namespace ServerUS {
    class ServerUS.StoryBuilder {
        - autore : String
        - data_creazione : String
        - descrizione : String
        - id : String
        - nome : String
        - nome_progetto : String
        - tag : String
        - versione : String
        + StoryBuilder()
        + StoryBuilder()
        + getAutore()
        + getData_creazione()
        + getDescrizione()
        + getId()
        + getNome()
        + getNome_progetto()
        + getTag()
        + getVersione()
        + print()
        + setAutore()
        + setData_creazione()
        + setDescrizione()
        + setNome()
        + setNome_progetto()
        + setTag()
        + setVersione()
    }
  }
  

  namespace ServerUS {
    interface ServerUS.UserInterface {
        {abstract} + check_db()
        {abstract} + check_db_resultSet()
        {abstract} + downloardUserStory()
        {abstract} + insertDDL_userStory()
        {abstract} + loadUserStory_DB()
        {abstract} + searchByTag()
        {abstract} + serachAllUserStoryfromDatabase_Icescrum()
        {abstract} + testRMI()
        {abstract} + viewUserStoryPNG()
    }
  }
  

  ServerUS.ServerUS .up.|> ServerUS.UserInterface
  ServerUS.ServerUS -up-|> java.rmi.server.UnicastRemoteObject
  ServerUS.StoryBuilder .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
