@startuml

title __INTERFACE_RULE's Class Diagram__\n

  namespace ClientUS {
    namespace NLP {
      namespace Interface_rule {
        interface ClientUS.NLP.Interface_rule.AC_RULE {
            {abstract} + AC1()
            {abstract} + AC2()
            {abstract} + AC3()
        }
      }
    }
  }
  

  namespace ClientUS {
    namespace NLP {
      namespace Interface_rule {
        interface ClientUS.NLP.Interface_rule.A_RULE {
            {abstract} + A1()
            {abstract} + A2()
            {abstract} + A3()
            {abstract} + A4()
            {abstract} + A5()
            {abstract} + A6()
            {abstract} + A7()
        }
      }
    }
  }
  

  namespace ClientUS {
    namespace NLP {
      namespace Interface_rule {
        interface ClientUS.NLP.Interface_rule.C_RULE {
            {abstract} + C1()
            {abstract} + C2()
            {abstract} + C3()
            {abstract} + C4()
            {abstract} + C5()
            {abstract} + C6()
            {abstract} + find_component_noun()
            {abstract} + fix_compound_noun_list()
        }
      }
    }
  }
  

  namespace ClientUS {
    namespace NLP {
      namespace Interface_rule {
        interface ClientUS.NLP.Interface_rule.H_RULE {
            {abstract} + H1()
            {abstract} + H2()
            {abstract} + H3()
        }
      }
    }
  }
  

  namespace ClientUS {
    namespace NLP {
      namespace Interface_rule {
        interface ClientUS.NLP.Interface_rule.R_RULE {
            {abstract} + R1()
            {abstract} + R2()
            {abstract} + R3()
            {abstract} + R4()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
